module.exports = {
  VM: require('./vm'),
  REDIS: require('./redis'),
  RDS: require('./rds'),
  MONITOR: require('./monitor'),
  IAM: require('./iam'),
  CPS: require('./cps'),
  DISK: require('./disk'),
  DATASTAR: require('./datastar'),
  MONGODB: require('./mongodb'),
  VPC: require('./vpc'),
  SOP: require('./sop'),
  XDATA: require('./xdata'),
  NC: require('./nc'),
  CLOUDDNSSERVICE: require('./clouddnsservice'),
  MPS: require('./mps'),
  JMR: require('./jmr'),
  STREAMBUS: require('./streambus'),
  OSS: require('./oss'),
  BASEANTI: require('./baseanti'),
  STREAMCOMPUTER: require('./streamcomputer'),
  JKE: require('./jke'),
  IPANTI: require('./ipanti')
}
